//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CART
    {
        public int ID { get; set; }
        public int CART_SHOP_ID { get; set; }
        public int CART_GOODS_ID { get; set; }
        public int CART_GOODS_NUM { get; set; }
        public int CART_USER_ID { get; set; }
    }
}
