//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FLOW
    {
        public int ID { get; set; }
        public int ORDER_ID { get; set; }
        public string ORDER_STATE_BRFORE { get; set; }
        public string ORDER_STATE_AFTER { get; set; }
        public string ACCOUNT { get; set; }
        public System.DateTime OPERATION_TIME { get; set; }
    }
}
