//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GOODS
    {
        public int ID { get; set; }
        public string GOODS_NAME { get; set; }
        public double GOODS_PRICE { get; set; }
        public string GOODS_TYPE { get; set; }
        public string GOODS_DESCRIBE { get; set; }
        public int GOODS_REPERTORY { get; set; }
        public int GOODS_SHOP_ID { get; set; }
        public string GOODS_IMAGE_URL { get; set; }
    }
}
