//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORDER
    {
        public int ID { get; set; }
        public int ORDER_USER_ID { get; set; }
        public System.DateTime ORDER_TIME { get; set; }
        public int ORDER_SHOP_ID { get; set; }
        public Nullable<int> ORDER_RIDER_ID { get; set; }
        public int ORDER_NO { get; set; }
        public int ORDER_ALLPRICE { get; set; }
        public string ORDER_STATE { get; set; }
    }
}
